name: 'Handle `site-built` repository dispatch event action'

on:
  repository_dispatch:
    types: [ 'deploy' ]

jobs:
  'ARTIFACT':
    runs-on: ubuntu-latest
    steps:
    - name: 'Download artifact'
      id: 'DOWNLOAD'
      uses: actions-rindeal/download-artifact@v4
      with:
        'artifact':     ${{ github.event.client_payload['artifact'] }}
        'github-token': ${{ secrets['CODE_ARTIFACT_TOKEN'] }}

    - name: 'Upload artifact'
      id: 'UPLOAD'
      uses: actions-rindeal/upload-artifact@v4
      with:
        'name': ${{ fromJSON(github.event.client_payload['artifact'])['name'] }}

    outputs:
      'environment': ${{ github.event.client_payload['environment'] }}
      'artifact':    ${{ steps.UPLOAD.outputs.ARTIFACT }}

  'TESTS':
    needs: 'ARTIFACT'
    runs-on: ubuntu-latest
    steps:
    - name: 'Trigger tests'
      uses: peter-evans/repository-dispatch@v3
      with:
        'event-type': 'test-site'
        'repository': ${{ vars['TESTER_REPO'] }}
        'client-payload': ${{ toJSON(needs['ARTIFACT'].outputs) }}
        'token': ${{ secrets['TESTER_DISPATCH_TOKEN'] }}
