name: 'Deploy'

on:
  workflow_dispatch:
    inputs:
      'environment':
        description: ''
        default: 'staging'
        type: choice
        options:
        - 'staging'
        - 'production'

      'artifact':
        description: 'JSON'
        required: true

jobs:
  'ARTIFACT':
    runs-on: ubuntu-latest
    steps:
    - name: 'Download artifact'
      id: 'DOWNLOAD'
      uses: 'actions-rindeal/download-artifact@v4'
      with:
        'artifact':     ${{ inputs['artifact'] }}
        'github-token': ${{ secrets['CODE_ARTIFACTS_RO_TOKEN'] }}

    - name: 'Upload artifact'
      id: 'UPLOAD'
      uses: 'actions-rindeal/upload-artifact@v4'
      with:
        'name': ${{ fromJSON(inputs['artifact'])['name'] }}

    outputs:
      'artifact': ${{ steps.UPLOAD.outputs['artifact'] }}

  'TESTS':
    needs: 'ARTIFACT'
    runs-on: ubuntu-latest
    steps:
    - name: 'Download artifact'
      id: 'DOWNLOAD'
      uses: 'actions-rindeal/download-artifact@v4'
      with:
        'artifact': ${{ needs['ARTIFACT'].outputs['artifact'] }}

  'DEPLOY':
    needs: [ 'ARTIFACT', 'TESTS' ]
    runs-on: ubuntu-latest
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: 'github-pages'
      url:  ${{ steps.DEPLOYMENT.outputs.page_url }}
    steps:
    - name: vardump
      run:
        for t in TEST{1..4}; do
          echo "$t='${!t}'"
        done
      env:
        TEST1: ${{ needs['ARTIFACT'].outputs['artifact']['name'] }}
        TEST2: ${{ needs['ARTIFACT'].outputs['artifact'].name }}
        TEST3: ${{ needs['ARTIFACT'].outputs.artifact['name'] }}
        TEST4: ${{ needs['ARTIFACT'].outputs.artifact.name }}
    - name: 'Deploy to GitHub Pages'
      id: 'DEPLOYMENT'
      if: inputs['environment'] == 'staging'
      uses: 'actions/deploy-pages@v4'
      with:
        artifact_name: ${{ needs['ARTIFACT'].outputs['artifact']['name'] }}
