name: 'Deploy'

on:
  workflow_dispatch:
    inputs:
      'environment':
        description: ''
        default: 'staging'
        type: choice
        options:
        - 'staging'
        - 'production'

      'artifact':
        description: 'JSON'
        required: true

jobs:
  'ARTIFACT':
    runs-on: ubuntu-latest
    steps:
    - name: 'Download artifact'
      id: 'DOWNLOAD'
      uses: 'actions-rindeal/download-artifact@v4'
      with:
        'artifact':     ${{ inputs['artifact'] }}
        'github-token': ${{ secrets['CODE_ARTIFACTS_RO_TOKEN'] }}

    - name: 'Upload artifact'
      id: 'UPLOAD'
      uses: 'actions-rindeal/upload-artifact@v4'
      with:
        'name': ${{ fromJSON(inputs['artifact'])['name'] }}

    outputs:
      'artifact': ${{ steps.UPLOAD.outputs['artifact'] }}

  'TESTS':
    needs: 'ARTIFACT'
    runs-on: ubuntu-latest
    steps:
    - name: 'Download artifact'
      id: 'DOWNLOAD'
      uses: 'actions-rindeal/download-artifact@v4'
      with:
        'artifact': ${{ needs['ARTIFACT'].outputs['artifact'] }}

  'DEPLOY':
    needs: [ 'ARTIFACT', 'TESTS' ]
    runs-on: ubuntu-latest
    steps:
    - name: 'Download artifact'
      id: 'DOWNLOAD'
      uses: 'actions-rindeal/download-artifact@v4'
      with:
        'artifact': ${{ needs['ARTIFACT'].outputs['artifact'] }}

    - name: 'Foo'
      id: 'DEPLOY'
      run: |
        echo Hello World
