name: 'Deploy'

on:
  repository_dispatch:
    types: [ 'deploy' ]

jobs:
  'ARTIFACT':
    runs-on: ubuntu-latest
    steps:
    - name: 'Generate token'
      id: 'TOKEN'
      uses: 'actions/create-github-app-token@v1'
      with:
        'app-id': ${{ vars['GHAPP__TOKGEN__ARTIFACT_PROXY__CONTENTS__RW__APP_ID'] }}
        'private-key': ${{ secrets['GHAPP__TOKGEN__ARTIFACT_PROXY__CONTENTS__RW__PRIVATE_KEY'] }}

    - name: 'Save artifact in a public proxy'
      uses: peter-evans/repository-dispatch@v3
      with:
        'event-type': 'save'
        'repository': ${{ vars['ARTIFACT_PROXY_REPO'] }}
        'client-payload': ${{ toJSON(github.event.client_payload) }}
        'token': ${{ steps.TOKEN.outputs['token'] }}

  'TESTS':
    needs: 'ARTIFACT'
    runs-on: ubuntu-latest
    steps:
    - name: 'Trigger tests'
      uses: peter-evans/repository-dispatch@v3
      with:
        'event-type': 'test-site'
        'repository': ${{ vars['TESTER_REPO'] }}
        'client-payload': ${{ toJSON(needs['ARTIFACT'].outputs) }}
        'token': ${{ secrets['TESTER_DISPATCH_TOKEN'] }}
