name: Site Deployment and Testing

on:
  repository_dispatch:
    types: [site-built]

jobs:
  process-artifact:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:

    - name: Setup
      id: SETUP
      run: |
        echo "SITE_DATA_DIR=${GITHUB_WORKSPACE}/site-data" >> $GITHUB_OUTPUT
    
    - name: Download artifact
      id: DOWNLOAD
      if: github.event_name == 'repository_dispatch'
      uses: actions/download-artifact@v4
      with:
        repository:   ${{ github.event.client_payload.ARTIFACT.WORKFLOW_RUN.REPOSITORY_FULL_NAME }}
        run-id:       ${{ github.event.client_payload.ARTIFACT.WORKFLOW_RUN.ID }}
        name:         ${{ github.event.client_payload.ARTIFACT.NAME }}
        github-token: ${{ secrets.CODE_ARTIFACT_TOKEN }}

    - name: Upload artifact
      id: UPLOAD
      uses: actions-rindeal/upload-artifact@v4
      with:
        name: ${{ github.event.client_payload.ARTIFACT.NAME }}
        path: ${{ github.event.client_payload.ARTIFACT.NAME }}.tar

    - name: Trigger tests
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.TESTER_DISPATCH_TOKEN }}
        repository: ${{ vars.TESTER_REPO }}
        event-type: test-site
        client-payload: |-
          {
            "environment": ${{ toJSON(github.event.client_payload.environment) }},
            "artifact": ${{ toJSON(fromJSON(steps.UPLOAD.outputs.ARTIFACT)) }}
          }          
