name: 'Save artifact from private code repo'

on:
  repository_dispatch:
    types: [ 'save' ]

jobs:
  'SAVE':
    runs-on: ubuntu-latest
    steps:
    - name: 'Download artifact'
      id: 'DOWNLOAD'
      uses: 'actions-rindeal/download-artifact@v4'
      with:
        'artifact':     ${{ github.event.client_payload['artifact'] }}
        'github-token': ${{ secrets['CODE_ARTIFACTS_RO_TOKEN'] }}

    - name: 'Upload artifact'
      id: 'UPLOAD'
      uses: actions-rindeal/upload-artifact@v4
      with:
        'name': ${{ fromJSON(github.event.client_payload['artifact'])['name'] }}

    outputs:
      'artifact': ${{ steps.UPLOAD.outputs.ARTIFACT }}
